baseURL = "https://lokal.ninja/rheinland-pfalz"
languageCode = "de-DE"
title = "Lokal Ninja - Rheinland-Pfalz"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  org = "lokal-ninja"
  region = "Rheinland-Pfalz"
  repo = "rheinland-pfalz"
